name: 'InferSharp'
description: 'Scalable and interprocedural code analyzer for detecting memory safety issues such as null pointer derefs and resource leaks.\n To detect issues on all files in the repo, try command shown in https://github.com/marketplace/actions/infersharp#basic-usage.\n To detect issues on changed files only, try command shown in https://github.com/marketplace/actions/infersharp#report-on-changed-files-only-from-pull-requests'
branding:
  icon: 'search'
inputs:
  binary-path:
    description: 'The path where the binaries (.dll and .pdb) are located.'
    required: true
  report-on-files:
    description: 'Only report on the files specified.'
    required: false
    default: ''
outputs:
  results:
    description: 'The analysis results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.binary-path }}
    - ${{ inputs.report-on-files }}
